"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
command_timeout = 500
format = "   $username$os$hostname$localip$shlvel$directory$git_branch$git_commit$git_state$git_metrics$git_status$docker_context$package$c$cmake$deno$golang$lua$python$rust$nix_shell$conda$aws$gcloud$openstack$azure$fill$cmd_duration$status$time$line_break$container$character"
palette = "catppuccin_mocha"
scan_timeout = 30

[character]
error_symbol = "[ó°³ ](red)"
success_symbol = "[ó°³ ](lavender)"

[cmd_duration]
format = "([\\[$duration ï‰’ \\]]($style) )"

[directory]
read_only = " ğŸ”’"
style = "bold blue"

[fill]
symbol = " "

[git_branch]
style = "bold purple"

[git_commit]
only_detached = true
style = "bold green"

[git_metrics]
disabled = true
format = "([î«œ $added]($added_style)) ([î«Ÿ $deleted]($deleted_style)) "

[git_state]
cherry_pick = "[îŠ› PICKING](bold yellow)"
merge = "[îœ§ MERGING](bold yellow)"
rebase = "[î¬€ REBASE](bold yellow)"

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
diverged = "ğŸ˜µ"
format = "([\\[](bold red)$all_status$ahead_behind[\\]](bold red) )"
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged = "[ó°“œ \\($count\\)](green)"
stashed = "ğŸ“¦"
untracked = "ğŸ¤·"
up_to_date = "[âœ“](green)"

[hostname]
ssh_only = true
style = "green"

[localip]
disabled = true
ssh_only = true
style = "flamingo"

[os]
disabled = false

[package]
disabled = true

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[status]
disabled = false
format = " [$symbol$status]($style) "

[time]
disabled = false

[username]
show_always = false
