[mgr]
linemode = "mtime"
scrolloff = 8
show_hidden = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
sort_translit = true

[[opener.edit]]
block = true
run = "helix $@"

[preview]
max_height = 1000
max_width = 1000
